### ISSUE TITLE
Binary ARMSID 2.15 for Arduino-ARMSID Updater

### ISSUE THREAD

**Issue by XadNightfall** [nobomi/Arduino-ARMSID-configurator#4]
Hi Nobomi,

Please when you have time update your ARMSID_FW_updaterr with the latest Binary 2.15 , i need to upgrade my armSID via arduino and not C64 .

Thanks.

**Comment by mlukasek** [comment]
GitHub updated https://github.com/nobomi/Arduino-ARMSID-configurator/blob/main/Arduino/ARMSID_FW_updater/firmware_for_Arduino_updater/ARMSID_Arduino-updater_fw215.zip
